IMAGE_NAME = "ubuntu/focal64"
K3S_VERSION = "v1.22.4+k3s1"
VM_CPU = "4"
VM_MEM = "8196"

Vagrant.configure("2") do |config|
  config.vm.box = IMAGE_NAME
  
  config.vm.define "k3s" do |k3s|
    
    ports = [8001,9110]
    ports.each do |port|
      config.vm.network "forwarded_port",
      guest: port,
      host: port,
      auto_correct: true
    end
      
    config.vm.provider "virtualbox" do |vb|
      vb.name = "vagrant-k3s-master"
      vb.cpus = VM_CPU
      vb.memory = VM_MEM
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
      vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
      
      config.vm.provision "install k3s",
        type: "shell",
        env: {"K3S_VERSION" => K3S_VERSION},
        inline: "curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE='644' INSTALL_K3S_EXEC='--no-deploy traefik' INSTALL_K3S_VERSION=$K8S_VERSION sh -"
      end
  end
end
